USE Session13
GO --01
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
--SELECT * FROM Product
SELECT * FROM Account

COMMIT TRAN
GO--02
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM Account

COMMIT TRAN
GO--03
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
UPDATE Account SET Balance = Balance - 1000 WHERE Id = 1

COMMIT TRAN
GO--04
BEGIN TRAN 
UPDATE Account SET Balance = Balance - 500 WHERE Id = 1
COMMIT TRAN
GO--05
BEGIN TRAN 
UPDATE Account SET Balance = Balance - 500 WHERE Id = 1
COMMIT TRAN
GO--06
BEGIN TRAN 
UPDATE Account SET Balance = Balance - 500 WHERE Id = 1
COMMIT TRAN
GO--07
BEGIN TRAN
INSERT INTO Account VALUES(5,'Sarah', 1000)

COMMIT TRAN
GO--08
BEGIN TRAN
INSERT INTO Account VALUES(7,'Sarah', 1000)

COMMIT TRAN
GO--09
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Account
COMMIT TRAN



