USE Session13
GO
EXEC USP_ResetAccounts
GO --01
BEGIN TRAN
UPDATE Account SET Balance = 500 WHERE Id = 1
UPDATE Account SET Balance = 1500 WHERE Id = 2
SELECT * FROM Account
ROLLBACK TRAN
COMMIT TRAN
GO--02
BEGIN TRAN
UPDATE Account SET Balance = 500 WHERE Id = 1
UPDATE Account SET Balance = 1500 WHERE Id = 2
SELECT * FROM Account
ROLLBACK TRAN
COMMIT TRAN
GO--03
BEGIN TRAN
UPDATE Account SET Balance = 500 WHERE Id = 1
UPDATE Account SET Balance = 1500 WHERE Id = 2
SELECT * FROM Account
ROLLBACK TRAN
COMMIT TRAN
GO--04
BEGIN TRAN 
SELECT * FROM Account
--...
--...
SELECT * FROM Account
COMMIT TRAN
GO--05
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN 
SELECT * FROM Account
--...
--...
SELECT * FROM Account
COMMIT TRAN
GO--06
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN 
SELECT * FROM Account WHERE Id = 2
--...
--...
SELECT * FROM Account
COMMIT TRAN
GO--07
INSERT INTO Account VALUES(10,'Scott', 1000),(11,'Bill',1000)
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN 
SELECT * FROM Account WHERE Id BETWEEN 1 AND 11
--...
--...
SELECT * FROM Account
COMMIT TRAN
GO--08
INSERT INTO Account VALUES(10,'Scott', 1000),(11,'Bill',1000)
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN 
SELECT * FROM Account WHERE Id BETWEEN 1 AND 11
--...
--...
SELECT * FROM Account
COMMIT TRAN
GO--09
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN 
SELECT * FROM Account 
--...
--...
SELECT * FROM Account
COMMIT TRAN






